### ISSUE TITLE
Raspberry Pi Touch Display does not wake up on touch

### ISSUE THREAD

**Issue by edmw** [edmw/volumio-diy#1]
After a certain amount of time the touch display does not wake up again.

Possible related error message in syslog is

`volumio kernel: rpi-backlight rpi_backlight: Backlight change failed`

**Comment by edmw** [comment]
May be related to https://github.com/raspberrypi/linux/issues/1179

**Comment by edmw** [comment]
Volumio 2 is built with kernel version 4.4.9.
Fix for https://github.com/raspberrypi/linux/issues/1179 is included in kernel version 4.4.37. 

Kernel versions: https://github.com/raspberrypi/firmware/commits/master
Build script for Volumio: https://github.com/volumio/Build

To use another kernel version change in file raspberryconfig.sh:
`echo y | SKIP_BACKUP=1 rpi-update 15ffab5493d74b12194e6bfc5bbb1c0f71140155`
to the hash of the desired kernel version.

**Comment by claudix** [comment]
I can confirm this issue on Raspberry PI 3. It's after about 30 minutes after screen goes blank that touch screen no longer responds. I'm currently running kernel 4.4.34 so I'm going to `sudo rpi-update` to see whether the latest updates in the kernel fix this problem or not.

**Comment by claudix** [comment]
OK, I've updated the kernel to 4.4.45 (running `sudo rpi-update`) and the problem has been solved!

**Comment by edmw** [comment]
Hi @claudix 
thanks for getting back on this. Good to know 4.4.45 resolved the problem. What distribution do you use? This particular issue is about a custom distribution called Volumio. With this `rpi-update` does not work out-of-the-box. So, this issue have to remain open until there is an update of Volumio unfortunately.

**Comment by claudix** [comment]
Oh, sad to hear that. I'm using Raspbian Jessie distro.

**Comment by edmw** [comment]
This should be solved for some time now with Volumio using a newer kernel version. I still have to test this with my setup. Closing this isssue nevertheless.
