### ISSUE TITLE
Startgeschwindigkeit

### ISSUE THREAD

**Issue by midre** [edmw/volumio-diy#6]
Hallo, 
Mein System läuft soweit reibungslos. Allerdings habe ich festgestellt, dass das booten bis zu dem Moment, an dem die Karten gescannt werden können 2-3 Minuten dauert. Also zu lange für ungeduldige Kinder. Hast Du eine Idee, woran das liegen kann?

Herzliche Grüße
Micha

**Comment by edmw** [comment]
Hallo Micha,
das Script zum Scannen wird als letztes Programm beim Booten gestartet. Das muss aber auch so sein, da es auf jeden Fall nach dem Volumio Server gestartet werden muss.

Trotzdem dauert es bei mir nicht mehrere Minuten, sondern etwa 30-40 Sekunden.

Zwei mögliche Ursachen fallen mir ein:
1. Deine SD Karte ist langsam. Hier gibt es merkbare Unterschiede. Ich kann auswendig leider gerade nicht sagen, welche Geschwindigkeitsklasse meine Karte hat.
2. Ich verwende inzwischen eine neuere Version von Volumio als 2.041. Leider konnte ich bisher die Dokumentation nicht aktualisieren. Allerdings hat das Einrichten auch bei der neuen Version fast wie beschrieben funktioniert. 

Ich würde es mit einer neuen und schnellen SD Karte versuchen und darauf auch eine neue Version von Volumio installieren.

Gruß
Michael

PS: Du kannst auch mal mit den Befehlen `systemd-analyze`, `systemd-analyze blame` und `systemd-analyze critical-chain` auf der Kommandozeile deinen Bootvorgang analysieren.

**Comment by midre** [comment]
Hallo Michael,

ich habe alles nochaml auf einen Raspi 3 aufgesetzt. Jetzt ist die Bootzeit ok.

Vielen Dank!
Micha
