### ISSUE TITLE
Spotify Playlists

### ISSUE THREAD

**Issue by mecaz** [edmw/volumio-diy#7]
Hello, 

is it possible to launch spotify playlist with rfid cards?

**Comment by e-p-s** [comment]
Is this project still alive?

**Comment by edmw** [comment]
Sure :-) Works for my son for almost 2 years now.

**Comment by edmw** [comment]
I had a look into the current API of volumio. It‘s in general possible to start Spotify playlists. Unfortunately this would require some kind of mapping between the cards and the playlists (with volumio‘s playlists this is done inside volumio‘s playlist management). 

While I‘m not using spotify it is unlikely that I‘ll find the time to implement this feature.

But of course, there is always the possibility to send a pull request.
